# Generated by Django 5.2.15 on 2026-06-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
