# Generated by Django 5.2.15 on 2026-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Order Placed', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.CharField(default='30 minutes', max_length=50),
        ),
    ]
