# Generated by Django 5.2.15 on 2026-06-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_boy',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
