# Generated by Django 5.2.15 on 2026-06-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('store', '0017_order_delivery_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryboy'),
        ),
    ]
