# Generated by Django 5.2.15 on 2026-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_assigned_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Picked Up', 'Picked Up'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=30),
        ),
    ]
